import type { Instrument } from "../types";

// Demo reference data. Prices are illustrative, not market data.
const eq = (i: Omit<Instrument, "asset_class" | "listed" | "tags"> & { tags?: string[] }): Instrument => ({
  asset_class: "equity",
  listed: true,
  ...i,
  tags: i.tags ?? [],
});

export const INSTRUMENTS: Instrument[] = [
  eq({ symbol: "TTE", name: "TotalEnergies", issuer: "TotalEnergies SE", country: "FR", exchange: "XPAR", currency: "EUR", price: 62.5, day_change_pct: 0.84, sector: "Energy", index: "CAC_40" }),
  eq({ symbol: "MC", name: "LVMH", issuer: "LVMH Moët Hennessy Louis Vuitton SE", country: "FR", exchange: "XPAR", currency: "EUR", price: 612.4, day_change_pct: -0.62, sector: "Consumer", index: "CAC_40" }),
  eq({ symbol: "AIR", name: "Airbus", issuer: "Airbus SE", country: "NL", exchange: "XPAR", currency: "EUR", price: 168.2, day_change_pct: 1.12, sector: "Industrials", index: "CAC_40" }),
  eq({ symbol: "BNP", name: "BNP Paribas", issuer: "BNP Paribas SA", country: "FR", exchange: "XPAR", currency: "EUR", price: 66.1, day_change_pct: 0.31, sector: "Financials", index: "CAC_40" }),
  eq({ symbol: "SAN", name: "Sanofi", issuer: "Sanofi SA", country: "FR", exchange: "XPAR", currency: "EUR", price: 91.8, day_change_pct: -0.18, sector: "Healthcare", index: "CAC_40" }),
  eq({ symbol: "SAP", name: "SAP", issuer: "SAP SE", country: "DE", exchange: "XETR", currency: "EUR", price: 228.5, day_change_pct: -1.04, sector: "Technology", index: "DAX" }),
  eq({ symbol: "SIE", name: "Siemens", issuer: "Siemens AG", country: "DE", exchange: "XETR", currency: "EUR", price: 186.4, day_change_pct: 0.57, sector: "Industrials", index: "DAX" }),
  eq({ symbol: "ALV", name: "Allianz", issuer: "Allianz SE", country: "DE", exchange: "XETR", currency: "EUR", price: 318.0, day_change_pct: 0.22, sector: "Financials", index: "DAX" }),
  eq({ symbol: "ASML", name: "ASML Holding", issuer: "ASML Holding NV", country: "NL", exchange: "XAMS", currency: "EUR", price: 684.0, day_change_pct: 1.46, sector: "Technology", index: "AEX" }),
  eq({ symbol: "VOLV-B", name: "Volvo B", issuer: "AB Volvo", country: "SE", exchange: "XSTO", currency: "SEK", price: 284.6, day_change_pct: 0.71, sector: "Industrials", index: "OMXS30" }),
  eq({ symbol: "ERIC-B", name: "Ericsson B", issuer: "Telefonaktiebolaget LM Ericsson", country: "SE", exchange: "XSTO", currency: "SEK", price: 81.9, day_change_pct: -0.44, sector: "Technology", index: "OMXS30" }),
  eq({ symbol: "ATCO-A", name: "Atlas Copco A", issuer: "Atlas Copco AB", country: "SE", exchange: "XSTO", currency: "SEK", price: 171.2, day_change_pct: 0.38, sector: "Industrials", index: "OMXS30" }),
  eq({ symbol: "INVE-B", name: "Investor B", issuer: "Investor AB", country: "SE", exchange: "XSTO", currency: "SEK", price: 289.4, day_change_pct: 0.12, sector: "Financials", index: "OMXS30" }),
  eq({ symbol: "ENEL", name: "Enel", issuer: "Enel S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 7.12, day_change_pct: 0.28, sector: "Utilities", index: "FTSE_MIB" }),
  eq({ symbol: "ISP", name: "Intesa Sanpaolo", issuer: "Intesa Sanpaolo S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 4.52, day_change_pct: 0.67, sector: "Financials", index: "FTSE_MIB" }),
  eq({ symbol: "UCG", name: "UniCredit", issuer: "UniCredit S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 48.3, day_change_pct: 1.21, sector: "Financials", index: "FTSE_MIB" }),
  eq({ symbol: "MONC", name: "Moncler", issuer: "Moncler S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 54.2, day_change_pct: -0.93, sector: "Consumer", index: "FTSE_MIB" }),
  eq({ symbol: "PRY", name: "Prysmian", issuer: "Prysmian S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 62.0, day_change_pct: 0.88, sector: "Industrials", index: "FTSE_MIB" }),
  eq({ symbol: "BRE", name: "Brembo", issuer: "Brembo S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 9.46, day_change_pct: -0.21, sector: "Consumer", index: "FTSE_MID", tags: ["eu_midcap"] }),
  eq({ symbol: "TGYM", name: "Technogym", issuer: "Technogym S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 10.84, day_change_pct: 0.46, sector: "Consumer", index: "FTSE_MID", tags: ["eu_sme"] }),
  eq({ symbol: "SES", name: "Sesa", issuer: "Sesa S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 92.5, day_change_pct: -0.54, sector: "Technology", index: "FTSE_SMALL", tags: ["eu_sme"] }),
  eq({ symbol: "ELN", name: "El.En.", issuer: "El.En. S.p.A.", country: "IT", exchange: "XMIL", currency: "EUR", price: 11.02, day_change_pct: 1.73, sector: "Healthcare", index: "FTSE_SMALL", tags: ["eu_sme"] }),
  eq({ symbol: "AAPL", name: "Apple Inc.", issuer: "Apple Inc.", country: "US", exchange: "XNAS", currency: "EUR", price: 215.0, day_change_pct: 0.94, sector: "Technology", index: "SP500" }),
  eq({ symbol: "MSFT", name: "Microsoft", issuer: "Microsoft Corp.", country: "US", exchange: "XNAS", currency: "EUR", price: 395.0, day_change_pct: 0.41, sector: "Technology", index: "SP500" }),
  {
    symbol: "IWDA",
    name: "iShares Core MSCI World UCITS ETF",
    issuer: "BlackRock (iShares)",
    country: "IE",
    exchange: "XAMS",
    currency: "EUR",
    price: 98.4,
    day_change_pct: 0.52,
    asset_class: "etf",
    sector: "Global equity",
    eu_equity_pct: 16,
    listed: true,
    tags: [],
  },
  {
    symbol: "CW8",
    name: "Amundi MSCI World (PEA, synthetic)",
    issuer: "Amundi",
    country: "FR",
    exchange: "XPAR",
    currency: "EUR",
    price: 542.1,
    day_change_pct: 0.49,
    asset_class: "etf",
    sector: "Global equity",
    eu_equity_pct: 75,
    listed: true,
    tags: ["synthetic_replication"],
  },
];
